### ISSUE TITLE
Download playlist doesn't seem to work

### ISSUE THREAD

**Issue by Amparose** [ritashugisha/Luxinate#7]
Pops up downloading prompt, which changes to download complete suspiciously fast. No videos are downloaded.

**Comment by stephen-bunn** [comment]
Most likely an issue with both Youtube and Youtube-dl’s implementation of playlists being changed. Currently working on a new version of Luxinate to solve issues like this.

Although sometimes there can be an underlying issue with either copyright security on Youtube videos or a broken connection.

**Comment by Amparose** [comment]
Awesome. Look forward to the new version. Downloading playlists would be an amazing time-saver.

**Comment by Amparose** [comment]
Any movement? Downloading single videos doesn't work now.

**Comment by stephen-bunn** [comment]
This project is slowly dropping in my priority list due to school and work taking a majority of my time. The current code is nowhere near release and a lot of the built-in resources are deprecated.
I do have a rewrite in progress, however that too is nowhere near completion.

 However, currently I find that the workflow is no longer benefiting me due to frequently working on a PC rather than my Mac. I tend to just use the youtube-dl and ffmpeg binaries instead of automating them through the workflow.

If anyone else wants to pick up this project (and refine it) they are welcome to.
I will be stating on the Alfred Forum that this workflow is deprecated and shouldn't be installed until the next version is released (hopefully by the end of this year)

**Comment by Amparose** [comment]
Thanks for head's up @ritashugisha, I'll try the youtube-dl binary via brew; good pointer! Good luck with your studies.
